using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Breeze.Core {

  public interface IEntityType {
    ///**
    // * @return The name of the EntityType
    // */
    //public String getName();
    ///**
    // * @param propertyName The name of the property to be returned.
    // * @return
    // */
    //public IProperty getProperty(String propertyName);
    //public boolean isComplexType();
    //public AutoGeneratedKeyType getAutoGeneratedKeyType();
    //public List<IDataProperty> getKeyProperties();
  //}
}

}
